commited API to get timesheet by reporting manager id
skStavir/colleagues-portal pull request #6
Opened 2023-11-16 07:48 UTC by devi-march

2023-11-16 07:59 UTC, skStavir commented on backend/server/getemptimeesheet-manger-id.js
> +const port = 3000;
We need all Apis to be part of the running server. So either 1. add it to the existing file or 2. split the Apis to multiple files with common server and db files.
You can do 1 first and get it merged
Then pick up 2 based on your time availability.

2023-11-16 08:02 UTC, skStavir requested changes
Please make sure that all the Apis work when you start the server

2023-11-16 17:38 UTC, skStavir commented on backend/server/getemptimeesheet-manger-id.js
> +const express = require("express");
why do we still need this file?
Shouldn't it be removed?

2023-11-17 11:44 UTC, devi-march commented
revertng

2023-11-17 12:11 UTC, devi-march commented on backend/server/getemptimeesheet-manger-id.js
> +const express = require("express");
removed

2023-11-19 07:17 UTC, skStavir approved these changes

2023-11-19 07:17 UTC, merged